Use `BigAutoField` as the primary key field
Starting from Django 3.2 this is the default for new projects/apps:
https://docs.djangoproject.com/en/stable/releases/3.2/#customizing-type-of-auto-created-primary-keys

Don't specify this with the `DEFAULT_AUTO_FIELD` setting because then it
would want to create the migration to `fcm_django` as well and running
`makemigrations --check` would fail.

Also, started to get this error so needed to add the `output_field` to
`MyDataMutation.__target_case`:
```
django.core.exceptions.FieldError: Expression contains mixed types:
CharField, BigAutoField. You must set output_field.
```